### ISSUE TITLE
Selecting apps and models in the view

### ISSUE THREAD

**Issue by dmussaku** [LegoStormtroopr/django-spaghetti-and-meatballs#11]
Thanks for creating this software. I wonder if its possible to add a functionality of choosing models and apps you want to see in the view (form in the template) Because i don't really like changing settings anytime i want to see a particular model. 
p.s. If you want i can contribute :)

**Comment by LegoStormtroopr** [comment]
Interesting thought, I presume you mean using a form to pick with apps/models to display?

It wouldn't be too hard to do, but I don't have time for it at the moment, if you have a suggestion I'd been keen to see it.
