### ISSUE TITLE
App names containing "."

### ISSUE THREAD

**Issue by techdragon** [LegoStormtroopr/django-spaghetti-and-meatballs#18]
Just added this to a project based on Django-cookiecutter which uses a hierarchical app structure. 
So the app names are '_foo.bar_', etc.

This seems to break the visualisation for some reason I have not yet determiened. Not in a great position to debug the issue at present, will update with more details once I have a chance.

**Comment by LegoStormtroopr** [comment]
Hey @techdragon why did you close this, happy to take a look at this if need be.

**Comment by LegoStormtroopr** [comment]
Oh wait... I just saw it was left open for a year. My bad :(

**Comment by tclancy** [comment]
Looks like this is still true on master?

**Comment by tclancy** [comment]
NVM, looks like you can make it work by dropping the prefix/ matching whatever the `app_name` is on the model.
