### ISSUE TITLE
App don't get any of the model fields

### ISSUE THREAD

**Issue by Whitie** [LegoStormtroopr/django-spaghetti-and-meatballs#19]
On my graphs popups all fields have "no such element ..." text. The graph is OK. See image.
![error_graph](https://cloud.githubusercontent.com/assets/6292770/19677474/c8f6831e-9a99-11e6-9aa1-89335a9dad25.png)

**Comment by LegoStormtroopr** [comment]
@Whitie, @brad has identified a solution for this which I've merged in and will have up on pypi later this week.
