### ISSUE TITLE
OneToOneFields not showing connections

### ISSUE THREAD

**Issue by chadgh** [LegoStormtroopr/django-spaghetti-and-meatballs#2]
See screenshot
https://goo.gl/photos/h4LR2Mf4iBtkzkYY9

The `work` and the `document` models have a `OneToOneField` relationships defined on the `work`.

**Comment by LegoStormtroopr** [comment]
One-to-one includes a bar and no arrows, is-a relations are shown using dotted lines.

![image](https://cloud.githubusercontent.com/assets/2173174/9623341/a8470eb0-5182-11e5-85c2-d80e823e8fb4.png)

**Comment by chadgh** [comment]
Nice. Thanks.

**Comment by LegoStormtroopr** [comment]
And this is now available on pip as version 0.1.2
