### ISSUE TITLE
Is version 0.2.0 released or not ? 

### ISSUE THREAD

**Issue by DESHRAJ** [LegoStormtroopr/django-spaghetti-and-meatballs#9]
I am trying to install version 0.2.0 but I think it is not released yet but given in the documentation.

**Comment by LegoStormtroopr** [comment]
Version 0.2.0 is on pypi: https://pypi.python.org/pypi/django-spaghetti-and-meatballs/0.2.0

What halfback when you try to install it?

**Comment by mb-senanga** [comment]
I can't install 0.2.0 either:

> Could not find a version that satisfies the requirement django-spaghetti-and-meatballs==0.2.0 (from versions: 0.1.0rc5, 0.1.0, 0.1.1)
> No matching distribution found for django-spaghetti-and-meatballs==0.2.0


I am using python 3 with django 1.8. Version 0.1.1 is only producing a blank screen

**Comment by internetmosquito** [comment]
This happened to me too, I had to install directly from github, add this to your requirements.txt file:

# django-spaghetti-and-meatballs==0.2.0
-e git+https://github.com/LegoStormtroopr/django-spaghetti-and-meatballs.git@master#egg=django-spaghetti-and-meatballs

**Comment by mb-senanga** [comment]
Thanks, that helped to install the new version. Unfortunately I still have a blank canvas..

**Comment by LegoStormtroopr** [comment]
I have a look into this today. Thanks for reporting it.

**Comment by LegoStormtroopr** [comment]
Ok, I tested and you are 100% correct. [Someone from StackOverflow pointed out ](http://stackoverflow.com/questions/35517285/cant-install-from-pypi-with-pip?noredirect=1#comment58725207_35517285)the whl file never went up. I'll fix this today.

**Comment by LegoStormtroopr** [comment]
Turns out I missed a step. Its now up on pip and works. Sorry for the inconvenience.

**Comment by internetmosquito** [comment]
That's great news :) :+1:
